### ISSUE TITLE
Consider PEP-8 compliance

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio-pypi#2]
I really like this API! But it has one drawback: The functions `runCompiler` and `generatePython` are not PEP-8 compliant. Please rename them to `run_compiler` (or maybe even just `run`) and `generate_python`. The argument names also need to be adapted.

**Comment by Mi-La** [comment]
Currently we tried to be consistent with rest of Zserio components (Zserio Python runtime, generated code). But I agree that at least in the pypi we could safely switch to PEP-8 style. It will be probably more expected by Python users who install Zserio via pip.
